a.out: main.o input_handler.o product.o mobile.o car.o tv.o user.o buyer.o controller.o offer.o order.o shop.o
	g++ -std=c++11 main.o input_handler.o product.o mobile.o car.o tv.o user.o buyer.o controller.o offer.o order.o shop.o -o a.out

main.o: main.cpp
	g++ -std=c++11 -c main.cpp

input_handler.o: input_handler.cpp
	g++ -std=c++11 -c input_handler.cpp

product.o: product.cpp
	g++ -std=c++11 -c product.cpp

mobile.o: mobile.cpp
	g++ -std=c++11 -c mobile.cpp

car.o: car.cpp
	g++ -std=c++11 -c car.cpp

tv.o: tv.cpp
	g++ -std=c++11 -c tv.cpp

user.o: user.cpp
	g++ -std=c++11 -c user.cpp

buyer.o: buyer.cpp
	g++ -std=c++11 -c buyer.cpp

controller.o: controller.cpp
	g++ -std=c++11 -c controller.cpp

offer.o: offer.cpp
	g++ -std=c++11 -c offer.cpp

order.o: order.cpp
	g++ -std=c++11 -c order.cpp

shop.o: shop.cpp
	g++ -std=c++11 -c shop.cpp